travis:
  secure:
    BINSTAR_TOKEN: SbwQBSBPI7Dbzru12d/+xIeJOBennUXp0VFNAbqGn4Hiod3shCrsbLjYQ4KUxuzadyq5HSI4Eg/CaLHOQin2p0c5tioQ1NeMZeKdidADjioE3EvFf2Gne78efBmSZfadSC5luZCMxeVU2+sTazA//wGGE1oUl9Cc02iDgO8/fzs/wChIO8SOKo+fhqXD+KU1Xr7UjI+xK4NEqM1Bqb07mz/M01ondmh1cW3UWhW6xHPO2aZJZwCIf4/eEYclZSZrQvQ8vLelQibJZayFi9z0XJC9oLPm8nGyaw6Gdg9uHQxZHh4tyIoiDKdqJ8Q2HcmO4kS+jfSSrHPo+F9xkRgbE8PVfhxSZCIK8pI5OI7BlOE+CEtUdarooWWju6VMu9Bu83UBwZUosriCU6FgTJMkKoZEJSuwvx9WDJ+Pm4UOYNncIW1wesnSxLtbGvYJliIVSWWCfMgbiDvc9V3AtI1JkSSWe2rEWiLhMO3j8OEAG48WVxr44glDsJhdLy5Kei7fHq1Vk8nQ6hzWt3kBRbsZYVI3pvO+SjXNrgcF+v2PMeqk7zxyGngKw4gy56959+QHEhPCDPjEcIIE1pNHicZKvGPd0yBCliMf6CaWuGqTvvQpc5BPkyJLTpBXnK+1R56z+YPQtk4bGuxU9Naq++6SYYSKgWB6/SfALjscU4oUvAE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
