travis:
  secure:
    BINSTAR_TOKEN: GGX4Ea02qYu4K0RBxQ+FJfqvWQIiyeS2CP038SKUcluPxItoyDNRYfhYgyrfoehEyVsI9wr/swvT95EkJzbMB5zjej4T/L+TGuv1kfUyW4n94Jywlnwliwid4ll479u5rqxGb/FRw0AuWXJqDhn+5AYLj9NaCy0RFVvnVckROLblLlcr6Dqnl+HnDtsQpzHzcrRnLIuGK5rBASCJ4IagUA0JRsd45l6o2MoOZN0pzXAXcRCrK9khFpZxEXo97bG7Q4VTSZT1D13Kpn2SadAU2X/kGLqmB6vjNKPN0uYb+I64sF21d3trO5ZyQTwVgirEWP/r6E+a3AfjHDZa1k39rOURsWgWhU0i0Ave/v7+NO0o4Noa92k8Mxhtkd1KsTDTv+IMaYwD8Zy8UtaAtREpakDeja+OJZy2y4r9MVw5l/1NLdPNSaIj/+5FybEyEDauVye6x8iShWORJfUgYU/TXQbdpUcsJOshwmMLKavdoZxbfQ1/V204i/qb+pUkKVZnIZrLkk3lkZ9X8e2LLJ0JuNZszjX1vdwpxgCCbxE39+D4AVCCDCFtDkg6Zh1tJGasz0pyAbWmb7H9Rk4qMi1W3O//KChLT3/l+87JLR48Efl9bLIlmEALnPI3xAz+qiqyQn7ttgmv1Bc7QVoj8Uemiild71n6w8bK3is/VhS3SpM=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
